### ISSUE TITLE
Option to keep hex values

### ISSUE THREAD

**Issue by jrmayhew33** [mark-nicepants/variables2json-docs#1]
I see an example the color values are kept in hex (as entered) but when I run it it shows as rgbt, is there a way to keep it as a hex value?  Currently heavy used of token studio and convert that export to sass using style dictionary, trying to replicate that with new variables feature.  Thanks for your work!

**Comment by mark-nicepants** [comment]
How would you like to process the alpha channel? Would love to find 1 way of exporting color values.

**Comment by AntonNiklasson** [comment]
Would it be possible to specify the alpha as the "fourth" position in the RGB color?

```
rgba(0, 0, 0, 0.5); <=> #00000088
```

**Comment by mark-nicepants** [comment]
Added this setting in the update of today: version 6 (1.0.4)
