### ISSUE TITLE
Is this still going to be maintained?

### ISSUE THREAD

**Issue by timsully** [mark-nicepants/variables2json-docs#16]
Wondering whether this should be leveraged as a long-term tool as in-developed composites feature seems really compelling. Please advise, @mark-nicepants

**Comment by joernroeder** [comment]
came to ask the same question

**Comment by kristojorg** [comment]
It seems to not be open source either :/

**Comment by mark-nicepants** [comment]
Sorry guys, after creating this plugin I changed jobs so my work focus is less on Figma at the moment. Im willing to invite some contributors to the source code. Any of you guys want to help developing the plugin?

**Comment by timsully** [comment]
> Sorry guys, after creating this plugin I changed jobs so my work focus is less on Figma at the moment. Im willing to invite some contributors to the source code. Any of you guys want to help developing the plugin?

Thank you for following up. I would love to contribute, but I am really only useful when it comes to designing and styling things on the front-end. One thing I could do is contribute to the plugin by updating the UI to be more accessible by essentially making "tap" targets bigger and conduct accessibility tests on the color to ensure it WCAG 3.0 compliant across the board if that interests you.

Or to implement any design ideas you have.

**Comment by mark-nicepants** [comment]
Sure, all help is most welcome! ill invite you to the figma file and will send you a figma link on Twitter.

**Comment by timsully** [comment]
> Sure, all help is most welcome! ill invite you to the figma file and will send you a figma link on Twitter.

Awesome, look forward to collaborating!

**Comment by kristojorg** [comment]
@mark-nicepants thanks for the response! Would you be willing to open source the plugin so we might contribute to it? I don't know I have the bandwidth to maintain it fully but would be happy to contribute any fixes/changes I need for my use case

**Comment by ryanzec** [comment]
@mark-nicepants @timsully Any plans to open source this plugin? 

I can understand if you longer want / can maintain it however continuing to use this plugin without knowing if it is still supported (it still works but the last update was a year in a half ago) is a bit concerning since if it does break in a future version of Figma, there is no ability to know I can continue to rely on this plugin (if is was open sourced, I would at least know I could fix it myself if needed as a worse case).

**Comment by mark-nicepants** [comment]
Sorry for not being able to do this sooner! I've open sources the repo here: https://github.com/mark-nicepants/variables2json. Ill accept collaborators and PR's for features and bugfixes!
