### ISSUE TITLE
Incorrect RGB values

### ISSUE THREAD

**Issue by saldridge13** [mark-nicepants/variables2json-docs#3]
First off, thanks for the great plugin!

I want to raise an issue that the RGB colour calculation is slightly off. For example, If I create a new variable in Figma and inspect it, the colour values are (R: 77, G: 116, B:255), but when I download the JSON file, the RGB values are: (R: 7**6**, G: 11**5**, B:255).
I know it's such a minor issue, but it has a major impact when trying to match a client's palette. It would be great to see these values match.

Thanks again!

**Comment by mark-nicepants** [comment]
Sounds like a rounding error! Ill have a look at it in the next version

**Comment by saldridge13** [comment]
That would be amazing! Thanks

**Comment by mark-nicepants** [comment]
Fixed this in the update of today! version 6 (v1.0.4). Was indeed a floor/rounding error!

**Comment by saldridge13** [comment]
@mark-nicepants Thank you so much! Looks good to me
