### ISSUE TITLE
Use plugin with view permissions

### ISSUE THREAD

**Issue by mbernabeu** [mark-nicepants/variables2json-docs#4]
Hello!

I can install and use the plugin without any problem when I have editing permissions

but if I try to install it from a user with only read permissions on the project, the plugin does not appear in the listings and does not give the possibility to install it.

Maybe it is a limitation or a bug? is there any way to use it so that those users can see and download the variables?

Thank you very much!

**Comment by mark-nicepants** [comment]
I'll have to check. There are no explicit limitations that I put in place, but maybe Figma limits what a person with read-only access can see and query.

**Comment by mark-nicepants** [comment]
This seems a limitation on Figma's side. Only plugins allowed are code generation. Maybe in the future we can investigate if this plugin qualifies for that
